using System.IO;
using System.Linq;
using NUnit.Framework;
using UnityEngine;

namespace SweetBazaar.Core.Tests
{
    // Checks the real levels.json that ships with the game (built with tools\build-levels.ps1).
    public class ShippedLevelPackTests
    {
        private const int ExpectedMinimumLevelCount = 200;

        private static string PackPath =>
            Path.Combine(Application.dataPath, "_Game", "Resources", "Levels", "levels.json");

        private static LevelPack Load() => LevelPackJson.Parse(File.ReadAllText(PackPath));

        [Test]
        public void PackFile_ParsesAndEveryLevelIsValid()
        {
            var pack = Load();

            Assert.GreaterOrEqual(pack.Count, ExpectedMinimumLevelCount);
            Assert.IsEmpty(pack.Validate());
        }

        [Test]
        public void PackCanBeLoadedTheWayTheGameWillLoadIt()
        {
            var asset = Resources.Load<TextAsset>("Levels/levels");

            Assert.IsNotNull(asset, "Resources.Load could not find Levels/levels");
            Assert.AreEqual(Load().Count, LevelPackJson.Parse(asset.text).Count);
        }

        [Test]
        public void NoLevelStartsWithAPackedBoxOrIsAlreadyWon()
        {
            foreach (var record in Load().Levels)
            {
                var board = Board.FromLevel(record.Definition);

                Assert.IsFalse(board.IsWon, $"level {record.Number}");
                Assert.IsFalse(board.Boxes.Any(box => box.IsClosed), $"level {record.Number}");
            }
        }

        [Test]
        public void NoLevelUsesMoreCandyTypesThanTheArtBudget()
        {
            foreach (var record in Load().Levels)
            {
                int types = record.Definition.Boxes.SelectMany(box => box).Distinct().Count();

                Assert.LessOrEqual(types, LevelCurve.MaxCandyTypes, $"level {record.Number}");
            }
        }

        // ---- difficulty: the game must keep getting harder, with no easy levels in between ----

        [Test]
        public void EveryLevelStoresItsMeasuredDifficulty()
        {
            foreach (var record in Load().Levels)
                Assert.GreaterOrEqual(record.WinRate, 0, $"level {record.Number}");
        }

        // Guards against a stale file: levels.json must have been generated by the current LevelCurve.
        // (After release, shipped levels are frozen and this check should be relaxed on purpose.)
        [Test]
        public void EveryLevelIsCloseToTheDifficultyTheCurveWants()
        {
            foreach (var record in Load().Levels)
            {
                var profile = LevelCurve.GetProfile(record.Number);

                Assert.That(record.WinRate, Is.InRange(
                    profile.TargetWinRate - profile.WinRateTolerance, profile.TargetWinRate + profile.WinRateTolerance),
                    $"level {record.Number}: bot wins {record.WinRate}%, the curve wants {profile.TargetWinRate}%");
            }
        }

        [Test]
        public void TheGameGetsHarderInSteps_NotBackAndForth()
        {
            var levels = Load().Levels;
            const int window = 20;

            double previous = double.MaxValue;
            for (int from = 0; from + window <= levels.Count; from += window)
            {
                double average = levels.Skip(from).Take(window).Average(l => l.WinRate);

                Assert.LessOrEqual(average, previous + 1.0, $"levels {from + 1}-{from + window} are easier than the 20 before");
                previous = average;
            }
        }

        [Test]
        public void NoLevelIsFarEasierThanTheOnesBeforeIt()
        {
            var levels = Load().Levels;

            for (int i = 10; i < levels.Count; i++)
            {
                double before = levels.Skip(i - 10).Take(10).Average(l => l.WinRate);

                Assert.LessOrEqual(levels[i].WinRate, before + 10.0,
                    $"level {levels[i].Number} (bot wins {levels[i].WinRate}%) is much easier than the 10 levels before it ({before:F0}%)");
            }
        }

        [Test]
        public void TheStoredDifficultyIsWhatTheBotStillMeasures()
        {
            var pack = Load();

            foreach (int number in new[] { 1, 15, 40, 80, 120, 200 })
            {
                var record = pack.Get(number);
                var board = Board.FromLevel(record.Definition);

                Assert.AreEqual(record.WinRate, LevelGenerator.MeasureWinRate(board, record.Seed, 100), $"level {number}");
            }
        }

        [Test]
        public void SampledLevels_AreSolvableWithTheStatedShortestSolution()
        {
            var pack = Load();

            foreach (int number in new[] { 1, 2, 3, 5, 10, 20, 50, 100, 150, 200 })
                AssertSolvesAsStated(pack.Get(number));
        }

        // The full check takes a few minutes: powershell -File tools\run-tests.ps1 -Filter AllLevels_AreSolvable
        [Test, Explicit("Solves every shipped level; takes a few minutes.")]
        public void AllLevels_AreSolvableWithTheStatedShortestSolution()
        {
            foreach (var record in Load().Levels)
                AssertSolvesAsStated(record);
        }

        private static void AssertSolvesAsStated(LevelRecord record)
        {
            var result = Solver.Solve(Board.FromLevel(record.Definition), new SolverOptions { MaxStates = 2000000 });

            Assert.AreEqual(SolveStatus.Solved, result.Status, $"level {record.Number}");
            Assert.AreEqual(record.MinMoves, result.Moves.Count, $"level {record.Number}");
        }
    }
}
